### ISSUE TITLE
Ideas on this error?

### ISSUE THREAD

**Issue by rufflereth** [rsaryev/talk-codebase#4]
Hi, after saying "Creating vector store will cost.... continue?" I get the following: 

`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1446,) + inhomogeneous part`

Any thoughts on why this might be?

**Comment by rsaryev** [comment]
What file format was uploaded? Before "Creating vector store will cost.... continue?" should be a list of files
📄 ....
📄 ...

**Comment by rufflereth** [comment]
Mix of mostly .ts and .py from a github repo. I'll give it a few more tries on sub directories.

**Comment by rufflereth** [comment]
I was able to get this working on sub-folders btw. Didn't figure out what was causing it on the main folder though. Cheers.
